### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by JokerQyou** [SnowMB/traefik-certificate-extractor#1]
First of all thank you for providing an alternative tool to manage SSL certificate with traefik. However I've found some issues with the README.

- The `Dockerfile` does not pass `-r` option by default. So if a user follows the README exactly, containers with matched label won't be restarted after the certificates having been extracted.
- The default Unix socket file is `/var/run/docker.sock` rather than `/var/run/docker.socket`. By following the README you'll get a `File not found error` when the script is trying to list containers with a specific label.

**Comment by SnowMB** [comment]
Fixed. Thank you for the contribution.
